# With CUDA_MPS_PINNED_DEVICE_MEM_LIMIT=''GPU-31cfe05c-ed13-cd17-d7aa-c63db5108c24=5GB,GPU-8d042338-e67f-9c48-92b4-5b55c7e5133c=10GB'' - 20 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mps-deployment-gpuburn
  labels:
    app: mps-deployment-gpuburn
spec:
  replicas: 20
  selector:
    matchLabels:
      app: mps-deployment-gpuburn
  template:
    metadata:
      labels:
        app: mps-deployment-gpuburn
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      hostPID: true
      containers:
        - name: gpu-burn
          image: nvidia/cuda:12.2.0-devel-ubuntu22.04
          command: ["/bin/bash", "-c", "--"]
          args:
            - |
              apt update && apt install -y build-essential git && \
              git clone https://github.com/wilicc/gpu-burn.git && \
              cd gpu-burn && make && \
              export CUDA_MPS_PINNED_DEVICE_MEM_LIMIT=''GPU-31cfe05c-ed13-cd17-d7aa-c63db5108c24=5GB,GPU-8d042338-e67f-9c48-92b4-5b55c7e5133c=10GB'' && \
              ./gpu_burn 120
          resources:
           limits:
             nvidia.com/gpu.shared: 1
